/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthRequest {
    #[serde(rename = "oculusId", skip_serializing_if = "Option::is_none")]
    pub oculus_id: Option<String>,
    #[serde(rename = "proof", skip_serializing_if = "Option::is_none")]
    pub proof: Option<String>,
    #[serde(rename = "steamId", skip_serializing_if = "Option::is_none")]
    pub steam_id: Option<String>,
}

impl AuthRequest {
    pub fn new() -> AuthRequest {
        AuthRequest {
            oculus_id: None,
            proof: None,
            steam_id: None,
        }
    }
}


