/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Instant {
    #[serde(rename = "epochSeconds", skip_serializing_if = "Option::is_none")]
    pub epoch_seconds: Option<i64>,
    #[serde(rename = "nanosecondsOfSecond", skip_serializing_if = "Option::is_none")]
    pub nanoseconds_of_second: Option<i32>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl Instant {
    pub fn new() -> Instant {
        Instant {
            epoch_seconds: None,
            nanoseconds_of_second: None,
            value: None,
        }
    }
}


