/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchResponse {
    #[serde(rename = "docs", skip_serializing_if = "Option::is_none")]
    pub docs: Option<Vec<crate::models::MapDetail>>,
    #[serde(rename = "redirect", skip_serializing_if = "Option::is_none")]
    pub redirect: Option<String>,
}

impl SearchResponse {
    pub fn new() -> SearchResponse {
        SearchResponse {
            docs: None,
            redirect: None,
        }
    }
}


