/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserDiffStats {
    #[serde(rename = "easy", skip_serializing_if = "Option::is_none")]
    pub easy: Option<i32>,
    #[serde(rename = "expert", skip_serializing_if = "Option::is_none")]
    pub expert: Option<i32>,
    #[serde(rename = "expertPlus", skip_serializing_if = "Option::is_none")]
    pub expert_plus: Option<i32>,
    #[serde(rename = "hard", skip_serializing_if = "Option::is_none")]
    pub hard: Option<i32>,
    #[serde(rename = "normal", skip_serializing_if = "Option::is_none")]
    pub normal: Option<i32>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl UserDiffStats {
    pub fn new() -> UserDiffStats {
        UserDiffStats {
            easy: None,
            expert: None,
            expert_plus: None,
            hard: None,
            normal: None,
            total: None,
        }
    }
}


