/*
 * BeatSaver API
 *
 * WIP  If you want to keep any kind of mirror instead of making 100s of requests instead consider subscribing to the websocket api. wss://ws.beatsaver.com/maps  Messages will be in the style {\"type\": \"MAP_UPDATE\", \"msg\": __MAP_DATA_HERE__}
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoteSummary {
    #[serde(rename = "downvotes", skip_serializing_if = "Option::is_none")]
    pub downvotes: Option<i32>,
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "key64", skip_serializing_if = "Option::is_none")]
    pub key64: Option<String>,
    #[serde(rename = "mapId", skip_serializing_if = "Option::is_none")]
    pub map_id: Option<i32>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f64>,
    #[serde(rename = "upvotes", skip_serializing_if = "Option::is_none")]
    pub upvotes: Option<i32>,
}

impl VoteSummary {
    pub fn new() -> VoteSummary {
        VoteSummary {
            downvotes: None,
            hash: None,
            key64: None,
            map_id: None,
            score: None,
            upvotes: None,
        }
    }
}


